theme: jekyll-theme-cayman

title: Music Playlists, Albums, Singles and more
email: clickonrefresh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 by clickonrefresh
twitter_username: clickonrefresh
github_username:  clickonrefresh
linkedin_username: clickonrefresh
