theme: jekyll-theme-cayman

title: Music Playlist 
  - by clickonrefresh
email: clickonrefresh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Music Playlists, Albums, Singles and more
twitter_username: clickonrefresh
github_username:  clickonrefresh
linkedin_username: clickonrefresh
